// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { CUSTOM_SUPABASE_URL as FALLBACK_SUPABASE_URL, CUSTOM_SUPABASE_PUBLISHABLE_KEY as FALLBACK_SUPABASE_PUBLISHABLE_KEY } from '@/supabase-config'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {

    const SUPABASE_URL = process.env['CUSTOM_SUPABASE_URL'] || FALLBACK_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env['CUSTOM_SUPABASE_PUBLISHABLE_KEY'] || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['CUSTOM_SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['CUSTOM_SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Add the custom Supabase secrets.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    // Self-hosted Supabase with symmetric (HS256) JWT: verify the token
    // locally with SUPABASE_JWT_SECRET — no network call back to the Auth
    // server (avoids hairpin-NAT hangs). Error behavior matches getClaims().
    const JWT_SECRET = process.env['SUPABASE_JWT_SECRET'];
    if (!JWT_SECRET) {
      const message = 'Missing Supabase environment variable(s): SUPABASE_JWT_SECRET. Add it to verify tokens locally.';
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    let claims: Record<string, unknown>;
    try {
      const { jwtVerify } = await import('jose');
      const { payload } = await jwtVerify(token, new TextEncoder().encode(JWT_SECRET), {
        algorithms: ['HS256'],
      });
      claims = payload;
    } catch {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!claims['sub']) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    return next({
      context: {
        supabase,
        userId: claims['sub'] as string,
        claims,
      },
    });
  },
);
